# Generated by Django 5.1.5 on 2026-06-24 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_categoria_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisponibilidadTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('intervalo_minutos', models.PositiveIntegerField(default=30)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'disponibilidad de turno',
                'verbose_name_plural': 'disponibilidades de turnos',
                'ordering': ['sala', 'dia_semana', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'sala',
                'verbose_name_plural': 'salas',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='turno',
            options={'ordering': ['fecha', 'hora'], 'verbose_name': 'turno', 'verbose_name_plural': 'turnos'},
        ),
        migrations.RemoveConstraint(
            model_name='turno',
            name='turno_unico_por_servicio_fecha_hora',
        ),
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('realizado', 'Realizado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='disponibilidadturno',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='app.sala'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='app.sala'),
        ),
        migrations.AddField(
            model_name='turno',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='app.sala'),
        ),
        migrations.AddConstraint(
            model_name='turno',
            constraint=models.UniqueConstraint(fields=('sala', 'fecha', 'hora'), name='turno_unico_por_sala_fecha_hora'),
        ),
        migrations.AddConstraint(
            model_name='disponibilidadturno',
            constraint=models.UniqueConstraint(fields=('sala', 'dia_semana', 'hora_inicio', 'hora_fin'), name='disponibilidad_unica_por_sala_dia_horario'),
        ),
    ]
