# Generated by Django 5.1.5 on 2026-10-02 00:04

import app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_turno_unico_sala_excepto_cancelados'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('costo_envio', models.DecimalField(decimal_places=2, default=4000, max_digits=10)),
                ('envio_gratis_desde', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('nombre_tienda', models.CharField(blank=True, max_length=150)),
                ('direccion_tienda', models.CharField(blank=True, max_length=255)),
                ('indicaciones_retiro', models.TextField(blank=True)),
                ('email_negocio', models.EmailField(blank=True, max_length=254)),
                ('comprobante_max_mb', models.PositiveSmallIntegerField(default=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CuentaTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('banco', models.CharField(max_length=120)),
                ('titular', models.CharField(max_length=150)),
                ('cuit', models.CharField(max_length=20)),
                ('alias', models.CharField(max_length=100)),
                ('cbu_cvu', models.CharField(max_length=30)),
                ('tipo_cuenta', models.CharField(max_length=80)),
                ('moneda', models.CharField(default='ARS', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('principal', models.BooleanField(default=False)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('activa', True), ('principal', True)), fields=('principal',), name='una_cuenta_principal_activa')],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(editable=False, max_length=14, unique=True)),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('pendiente_pago', 'Pendiente pago'), ('pago_informado', 'Pago informado'), ('confirmado', 'Confirmado'), ('preparando', 'Preparando'), ('listo', 'Listo'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='nuevo', max_length=20)),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('informado', 'Informado'), ('acreditado', 'Acreditado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('comprador_nombre', models.CharField(max_length=100)),
                ('comprador_apellido', models.CharField(max_length=100)),
                ('comprador_email', models.EmailField(max_length=254)),
                ('comprador_telefono', models.CharField(max_length=40)),
                ('comprador_dni', models.CharField(max_length=20)),
                ('tipo_factura', models.CharField(choices=[('B', 'Factura B'), ('A', 'Factura A'), ('E', 'Factura E')], default='B', max_length=1)),
                ('facturacion_mismos_datos', models.BooleanField(default=True)),
                ('facturacion_nombre', models.CharField(blank=True, max_length=100)),
                ('facturacion_apellido', models.CharField(blank=True, max_length=100)),
                ('facturacion_dni', models.CharField(blank=True, max_length=20)),
                ('facturacion_cuit', models.CharField(blank=True, max_length=20)),
                ('facturacion_razon_social', models.CharField(blank=True, max_length=150)),
                ('facturacion_domicilio', models.CharField(blank=True, max_length=255)),
                ('facturacion_condicion_iva', models.CharField(blank=True, max_length=30)),
                ('facturacion_pais', models.CharField(blank=True, max_length=100)),
                ('tipo_entrega', models.CharField(choices=[('retiro', 'Retiro por tienda'), ('envio', 'Envío a domicilio')], max_length=10)),
                ('receptor_mismos_datos', models.BooleanField(default=True)),
                ('receptor_nombre', models.CharField(blank=True, max_length=100)),
                ('receptor_apellido', models.CharField(blank=True, max_length=100)),
                ('receptor_dni', models.CharField(blank=True, max_length=20)),
                ('receptor_telefono', models.CharField(blank=True, max_length=40)),
                ('envio_calle', models.CharField(blank=True, max_length=120)),
                ('envio_altura', models.CharField(blank=True, max_length=20)),
                ('envio_piso_departamento', models.CharField(blank=True, max_length=60)),
                ('envio_localidad', models.CharField(blank=True, max_length=100)),
                ('envio_provincia', models.CharField(blank=True, max_length=100)),
                ('envio_codigo_postal', models.CharField(blank=True, max_length=20)),
                ('envio_referencias', models.TextField(blank=True)),
                ('medio_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], max_length=15)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_envio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock_reintegrado', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField()),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialEstadoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, max_length=20)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='app.pedido')),
            ],
            options={
                'ordering': ['fecha', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ComprobanteTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archivo', models.FileField(upload_to=app.models.comprobante_upload_to)),
                ('nombre_original', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('tamanio', models.PositiveIntegerField()),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comprobante', to='app.pedido')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_nombre', models.CharField(max_length=100)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.producto')),
            ],
        ),
    ]
