# Generated by Django 5.1.5 on 2026-10-02 00:10

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_configuracioncheckout_cuentatransferencia_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracioncheckout',
            name='comprobante_max_mb',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='configuracioncheckout',
            name='costo_envio',
            field=models.DecimalField(decimal_places=2, default=4000, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='configuracioncheckout',
            name='envio_gratis_desde',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
