# Generated by Django 5.1.5 on 2026-10-02 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_configuracioncheckout_comprobante_max_mb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.CharField(choices=[('retiro', 'Retiro en tienda'), ('envio', 'Envío a domicilio')], max_length=10),
        ),
    ]
