# Generated by Django 5.1.5 on 2026-10-02 21:55

import ckeditor_uploader.fields
from django.db import migrations, models


PREGUNTAS_INICIALES = (
    (
        "¿Cómo solicito un turno?",
        "Guía para reservar una consulta desde el sitio.",
        "<p>Iniciá sesión, elegí un servicio y consultá los horarios disponibles. Completá los datos solicitados y revisá la confirmación antes de finalizar.</p>",
    ),
    (
        "¿Dónde consulto o cancelo mis turnos?",
        "Ubicación y gestión de turnos del cliente.",
        "<p>En la sección <strong>Mis turnos</strong> podés consultar tus reservas. Si necesitás cancelar una, utilizá la opción disponible allí o comunicate con el equipo de Patitas Vet.</p>",
    ),
    (
        "¿Cómo compro productos?",
        "Pasos generales para comprar productos del catálogo.",
        "<p>Iniciá sesión, agregá productos al carrito y elegí <strong>Finalizar compra</strong>. Antes de confirmar, el sitio verifica nuevamente precios y disponibilidad.</p>",
    ),
    (
        "¿Qué opciones de entrega hay?",
        "Opciones de retiro y envío disponibles durante la compra.",
        "<p>Durante el checkout podés elegir las opciones disponibles de retiro en tienda o envío a domicilio. El costo del envío y el total se muestran antes de confirmar el pedido.</p>",
    ),
    (
        "¿Qué medios de pago aceptan?",
        "Información general sobre efectivo y transferencia.",
        "<p>Las opciones disponibles se muestran al finalizar la compra. Si elegís transferencia bancaria, deberás adjuntar el comprobante para informar el pago.</p>",
    ),
    (
        "¿Qué hago ante una urgencia veterinaria?",
        "Orientación básica ante situaciones urgentes.",
        "<p>Si tu mascota necesita atención inmediata, contactá a una guardia veterinaria. Los turnos y formularios online no sustituyen la atención de urgencia.</p>",
    ),
)


def crear_preguntas_frecuentes(apps, schema_editor):
    PreguntaFrecuente = apps.get_model("app", "PreguntaFrecuente")
    PreguntaFrecuente.objects.using(schema_editor.connection.alias).bulk_create([
        PreguntaFrecuente(pregunta=pregunta, descripcion=descripcion, contenido=contenido,
                          activo=True, orden=numero)
        for numero, (pregunta, descripcion, contenido) in enumerate(PREGUNTAS_INICIALES, start=1)
    ])


def eliminar_preguntas_iniciales(apps, schema_editor):
    PreguntaFrecuente = apps.get_model("app", "PreguntaFrecuente")
    for numero, (pregunta, descripcion, contenido) in enumerate(PREGUNTAS_INICIALES, start=1):
        PreguntaFrecuente.objects.using(schema_editor.connection.alias).filter(
            pregunta=pregunta, descripcion=descripcion, contenido=contenido, orden=numero,
        ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_pedido_tipo_entrega'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntaFrecuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pregunta', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField()),
                ('contenido', ckeditor_uploader.fields.RichTextUploadingField()),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'pregunta frecuente',
                'verbose_name_plural': 'preguntas frecuentes',
                'ordering': ['orden', 'pregunta'],
            },
        ),
        migrations.RunPython(crear_preguntas_frecuentes, eliminar_preguntas_iniciales),
    ]
